#%RAML 1.0 NamedExample
   [ {
      "id":37,
      "first":"John",
      "last":"Mike",
      "department":"DevOps"
    },
     {
      "id":37,
      "first":"Simon",
      "last":"Alexander",
      "department":"DevOps"
    }
   ]
    
